# Generated by Django 5.2.17 on 2026-10-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_options_alter_product_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('sku__regex', '^[A-Z0-9]+(-[A-Z0-9]+)*$')), name='variant_sku_format', violation_error_message='SKU must use uppercase letters and digits separated by single hyphens, e.g. OSLO-L-GRY.'),
        ),
    ]
