# Generated by Django 5.2.17 on 2026-10-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productvariant_variant_sku_format'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_hex',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('compare_at_price__isnull', True), ('compare_at_price__gt', models.F('price')), _connector='OR'), name='variant_compare_at_gt_price', violation_error_message='Compare-at price must be higher than the price.'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('color_hex__regex', '^(#[0-9A-Fa-f]{6})?$')), name='variant_color_hex_format', violation_error_message='Colour must be blank or a hex code like #E3DDD1.'),
        ),
    ]
