// Design tokens ported 1:1 from the Stitch export (DESIGN.md / code.html).
/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#426e52",
        "surface-variant": "#e5e2db",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#002110",
        "on-primary": "#ffffff",
        "on-primary-container": "#ffddca",
        primary: "#6e4326",
        "surface-container-highest": "#e5e2db",
        "on-surface": "#1c1c17",
        "surface-container-low": "#f6f3ec",
        "tertiary-fixed": "#bdeecb",
        "primary-fixed-dim": "#f7b994",
        "primary-container": "#8a5a3b",
        "secondary-container": "#e5e2de",
        surface: "#fcf9f1",
        "on-surface-variant": "#51443d",
        "on-secondary-fixed": "#1c1c1a",
        "on-secondary-container": "#656461",
        error: "#ba1a1a",
        "on-tertiary-fixed-variant": "#234f35",
        "on-secondary-fixed-variant": "#474744",
        "outline-variant": "#d6c3b9",
        secondary: "#5f5e5c",
        background: "#fcf9f1",
        "inverse-on-surface": "#f4f0e9",
        "inverse-primary": "#f7b994",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#673c20",
        "inverse-surface": "#31312c",
        "primary-fixed": "#ffdbc8",
        "on-tertiary-container": "#bdeecb",
        "secondary-fixed": "#e5e2de",
        "on-error": "#ffffff",
        "surface-bright": "#fcf9f1",
        "secondary-fixed-dim": "#c8c6c3",
        "tertiary-fixed-dim": "#a2d2b0",
        "surface-container": "#f1eee6",
        "surface-container-high": "#ebe8e0",
        "surface-tint": "#825335",
        outline: "#84746c",
        "error-container": "#ffdad6",
        "surface-dim": "#dcdad2",
        "on-error-container": "#93000a",
        tertiary: "#2a553b",
        "on-background": "#1c1c17",
        "on-primary-fixed": "#311300",
      },
      maxWidth: { "7xl": "none" },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-2xl": "4rem",
        "space-2xs": "0.25rem",
        "space-3xl": "6rem",
        "space-lg": "1.5rem",
        gutter: "1.5rem",
        "margin-tablet": "2rem",
        "gutter-desktop": "2rem",
        "space-xs": "0.5rem",
        "space-md": "1rem",
        "space-sm": "0.75rem",
        margin: "1rem",
        "space-xl": "2.5rem",
        "margin-desktop": "4rem",
      },
      fontFamily: {
        display: ["EB Garamond"],
        "label-md": ["Manrope"],
        "headline-lg": ["EB Garamond"],
        "body-sm": ["Manrope"],
        "display-mobile": ["EB Garamond"],
        title: ["Manrope"],
        "body-lg": ["Manrope"],
        "headline-md": ["EB Garamond"],
        "label-lg": ["Manrope"],
        "label-caps": ["Manrope"],
        "headline-lg-mobile": ["EB Garamond"],
        "currency-price": ["Manrope"],
        "body-md": ["Manrope"],
        "headline-sm": ["Manrope"],
      },
      fontSize: {
        display: [
          "56px",
          { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "400" },
        ],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" },
        ],
        "headline-lg": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "400" },
        ],
        "body-sm": [
          "13px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" },
        ],
        "display-mobile": [
          "38px",
          { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "400" },
        ],
        title: [
          "16px",
          { lineHeight: "24px", letterSpacing: "0em", fontWeight: "600" },
        ],
        "body-lg": [
          "17px",
          { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" },
        ],
        "headline-md": [
          "28px",
          { lineHeight: "36px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "label-lg": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" },
        ],
        "label-caps": [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "30px",
          { lineHeight: "36px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "currency-price": [
          "16px",
          { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-md": [
          "15px",
          { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "headline-sm": [
          "20px",
          { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
