# Generated by Django 5.2.17 on 2026-10-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_number_order_reservation_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='status',
        ),
    ]
