# Generated by Django 5.2.17 on 2026-09-28 22:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('MPESA', 'M-Pesa'), ('STRIPE', 'Stripe')], max_length=20)),
                ('method', models.CharField(choices=[('MPESA_STK', 'M-Pesa STK'), ('CARD', 'Card')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUND_PENDING', 'Refund Pending'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_gt_zero')],
            },
        ),
    ]
